# Generated by Django 5.0.6 on 2024-07-12 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_admin', '0002_user_is_active_user_is_staff_user_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
